CREATE TABLE IF NOT EXISTS natural_areas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    type TEXT,
    description TEXT,
    status TEXT,
    ownership TEXT,
    management TEXT,
    coordination TEXT,
    address TEXT,
    acres REAL,
    location TEXT,
    county TEXT,
    gps_coordinates TEXT,
    plus_code TEXT,
    trail_role TEXT,
    parent_trail_name TEXT,
    trail_segment_type TEXT,
    trail_access_type TEXT,
    trail_length_miles REAL,
    features TEXT,
    notes TEXT,
    url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);