#!/usr/bin/env python3
# =============================================================================
# SUPERSEDED — IMP-091 (2026-05-04)
# This monolithic pipeline script has been replaced by the parameterised model:
#   utilities/na_run_county.py + County_Spreadsheets/{County}/{county}_pipeline_config.json
# Do not use for new county runs. Kept for reference only.
# =============================================================================
"""
defiance_oh_pipeline.py — Defiance County, Ohio — Natural Areas Project Pipeline
RUN_ID: defiance_oh_2026_04_19  |  PREFIX: DEF
Stages: Resolution (1) → Normalization (2) → GPS (3) → TSV (4) → Vocab Gate (4.5)
        → Integrity Check (5) → DB Upsert (6)
"""

import argparse
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Path setup ────────────────────────────────────────────────────────────────
THIS_DIR   = Path(__file__).parent
# County_Spreadsheets/Defiance → County_Spreadsheets → Natural Areas Project v5
PROJECT_ROOT = THIS_DIR.parent.parent
UTILS_DIR    = PROJECT_ROOT / "utilities"
sys.path.insert(0, str(UTILS_DIR))

from na_pipeline_core import (
    SITE_TSV_COLUMNS, TRAIL_TSV_COLUMNS, TRAIL_SEGMENT_TSV_COLUMNS,
    TRAIL_NETWORK_TSV_COLUMNS, SITE_NETWORK_TSV_COLUMNS, AP_TSV_COLUMNS,
    acquire_gps, propagate_gps_to_children, propagate_gps_to_trails,
    propagate_gps_to_aps, add_plus_codes, add_gis_lookup,
    run_vocab_gate, write_all_tsvs, integrity_check,
    upsert_sites, upsert_site_parents, upsert_trails, upsert_trail_parents,
    upsert_access_points, upsert_run_metadata,
)

# ── Run config ────────────────────────────────────────────────────────────────
RUN_ID     = "defiance_oh_2026_04_19"
COUNTY     = "Defiance"
STATE      = "OH"
RUN_DATE   = "2026-04-19"
PREFIX     = "DEF"
NOW        = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
OUTPUT_DIR = str(THIS_DIR)
DEFAULT_DB = str(PROJECT_ROOT / "NASqlite" / "natural_areas_v5.db")

# ════════════════════════════════════════════════════════════════════════════════
#  STAGE 1 — RESOLUTION (mechanical; all Defiance entities are unique within run)
#  STAGE 2 — NORMALIZATION (hardcoded normalized dicts below)
# ════════════════════════════════════════════════════════════════════════════════

SITES = [
    # ── Tier 2: State ─────────────────────────────────────────────────────────
    {
        "site_id":          "DEF-S-001",
        "name":             "Independence Dam State Park",
        "category":         "Park",
        "subtype":          "",
        "designation":      "State Park",
        "status":           "Active",
        "ownership":        "State of Ohio",
        "governance":       "Ohio Department of Natural Resources, Division of Parks and Watercraft",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "Located on the banks of the Maumee River, the park features ruins of the Miami and Erie Canal and a three-mile hiking trail following the historic canal towpath that meanders between the old canal and the river through a dense hardwood forest. Over 200 bird species have been recorded. The park is along the Maumee State Scenic River.",
        "location":         "27722 County Rd 424, Defiance, Ohio 43512; approximately 3 miles east of Defiance on the Maumee River",
        "acres":            591.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Camping;Boat Ramp;Marina;Pavilion;Hiking Trail;Restrooms;Fire Ring;Picnic Area;Historic Lock",
        "features_raw":     "Primitive camping (tent only, April 1–Oct 31); boat launch (4-lane); marina; picnic shelters (reservable); hiking trail; hand-launch area; pit latrines; fire rings; picnic tables; Lock Number 13 ruins (Miami and Erie Canal)",
        "notes":            "NCT/Buckeye Trail routes through park along canal towpath. CONFIRM: 25 vs 40 primitive campsites (sources conflict). NID baseline seed 'Independence Dam (NID)' resolves to park infrastructure, not separate entity.",
        "url_primary":      "https://ohiodnr.gov/go-and-do/plan-a-visit/find-a-property/independence-dam-state-park-campground",
        "urls":             "https://www.stateparks.com/independence_dam_state_park_in_ohio.html;https://en.wikipedia.org/wiki/Independence_Dam_State_Park;https://dam.assets.ohio.gov/image/upload/ohiodnr.gov/documents/parks/parkmaps/independenceparkmap.pdf",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-002",
        "name":             "Oxbow Lake Wildlife Area",
        "category":         "Wildlife Area",
        "subtype":          "State Wildlife Area",
        "designation":      "State Wildlife Area",
        "status":           "Active",
        "ownership":        "State of Ohio",
        "governance":       "Ohio Department of Natural Resources, Division of Wildlife",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "Located in the glaciated lake plain of northwestern Ohio with slightly rolling topography. Mud Creek bisects the area, featuring large cottonwoods and sycamores along its banks, while upland woods consist mostly of oaks and hickories. Substantial areas of brushland and meadow are maintained for upland game habitat. Ohio purchased the originally forested land in 1948 after it had been cleared for farming in the previous century.",
        "location":         "Defiance County, Ohio; near Defiance, Bryan, and Napoleon",
        "acres":            416.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Boat Ramp;Parking Lot;Hiking Trail;Fishing Area;ADA Accessible",
        "features_raw":     "Boat ramp; parking lots (3 total — 1 at Little Oxbow Lake, 2 at Big Oxbow Lake); 1.25-mile stone walkway around reservoir with benches; handicapped parking near boat ramp; fishing area; idle speed only boating",
        "notes":            "Contains Big Oxbow Lake (38 ac) and Little Oxbow Lake (4.5 ac). Flag DEF-F-06: 'western agreement parcel' — no evidence found; UNRESOLVED. NID 'Oxbow Lake Dam' resolves to infrastructure, not separate entity. Fishing: northern pike, largemouth bass, bluegills, bullheads.",
        "url_primary":      "https://ohiodnr.gov/go-and-do/plan-a-visit/find-a-property/oxbow-lake-fishing-area",
        "urls":             "https://dam.assets.ohio.gov/image/upload/ohiodnr.gov/documents/wildlife/wildlife-area-maps/oxbow.pdf;https://www.stateparks.com/oxbow_lake_wildlife_area_in_ohio.html",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-003",
        "name":             "Winchester's Camp No. 3 / Fort Starvation",
        "category":         "Historic Site",
        "subtype":          "Historic Landmark",
        "designation":      "",
        "status":           "Active",
        "ownership":        "State of Ohio",
        "governance":       "Ohio Department of Natural Resources",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "War of 1812 winter encampment site (Nov. 2, 1812 – Jan. 1, 1813) for three Kentucky Militia Regiments and one regiment of US Regulars under Colonel Wells, stationed approximately six miles below Fort Winchester on the north bank of the Maumee River. Nicknamed 'Fort Starvation' by soldiers due to supply shortages. Believed burial site of approximately 300 Kentucky soldiers; thousands of bones were disturbed when the Miami and Erie Canal was dug through the burial ground (1837–1848) and reinterred. Historical marker erected 2010 by Defiance County Chapter Ohio Genealogical Society and other organizations.",
        "location":         "Four miles east of the City of Defiance on US Route 424 on the bank of the Maumee River, within Independence Dam State Park",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Historic Marker",
        "features_raw":     "Historical marker",
        "notes":            "ODNR Historic Site #24. Also known as 'Old Kentucky Burial Grounds.' Child site within Independence Dam State Park (DEF-S-001). GPS propagated from parent site.",
        "url_primary":      "https://www.hmdb.org/m.asp?m=37924",
        "urls":             "https://www.defiancecountygenealogy.org/Military/Kentucky.html",
        "parent_site_id":   "DEF-S-001",
    },

    # ── Tier 3: District (SWCD) ───────────────────────────────────────────────
    {
        "site_id":          "DEF-S-004",
        "name":             "Penney Nature Center",
        "category":         "Nature Preserve",
        "subtype":          "County Nature Preserve",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Defiance County",
        "governance":       "Defiance Soil and Water Conservation District",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A 78-acre nature preserve featuring wetlands, prairie lands, and woodlands, promoting conservation through education for all to enjoy. Land was gifted by the Penney family to Defiance County and is managed by the Defiance Soil and Water Conservation District.",
        "location":         "08855 Ashpacher Road, Defiance, OH 43512",
        "acres":            78.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Hiking Trail;Pavilion;Bridge;Interpretive Sign;Kiosk;Parking Lot",
        "features_raw":     "5 trails (3.5 miles total); pavilion with picnic tables; 2 bridges (walking bridge + covered bridge); educational signs (9); trailhead sign with map; improved parking lot; Storybook Trail (seasonal, ~0.5 mile)",
        "notes":            "Managed by Defiance SWCD per ORC Chapter 1515. Open dawn to dusk. ADDRESS: 'Aschpacher Road' vs 'Ashpacher Road' — spelling discrepancy between sources; verify. Storybook Trail (seasonal) is a separate Trail entity (DEF-T-004).",
        "url_primary":      "https://www.defianceswcd.org/penney-nature-center.html",
        "urls":             "https://visitdefianceohio.com/business-directory/penney-nature-center/",
        "parent_site_id":   "",
    },

    # ── Tier 4: County ────────────────────────────────────────────────────────
    {
        "site_id":          "DEF-S-005",
        "name":             "Auglaize Village",
        "category":         "Cultural Facility",
        "subtype":          "Heritage Center",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Defiance County",
        "governance":       "Defiance County Historical Society",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A living history village founded in 1966 by the Defiance County Historical Society that preserves the history of the men and women who carved a community out of the Great Black Swamp, featuring restored and reconstructed 19th-century buildings, farm museums, and multiple specialty museums.",
        "location":         "12296 Krouse Road, Defiance, OH 43512",
        "acres":            120.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Historic Structure;Museum Building;Guided Tours",
        "features_raw":     "Restored/reconstructed historic buildings (22+ structures); farm museums (4); military museum; natural history museum; model railroad museum; guided tours; virtual tour available; StoryMap interactive tour; event venue; tractor shows; reenactments; paranormal tours",
        "notes":            "County-owned; managed by Defiance County Historical Society (501c3 nonprofit). VERIFY_GOVERNANCE: confirm county ownership vs. long-term lease/deed (flag DEF-F-05). Open during events + volunteer work days (Tue 8am-2pm); tours by appointment. Also known as 'AuGlaize Village'.",
        "url_primary":      "https://www.auglaizevillage.org/",
        "urls":             "https://visitdefianceohio.com/explore/auglaize-village/;https://ohio.org/things-to-do/destinations/auglaize-village",
        "parent_site_id":   "",
    },

    # ── Tier 6: Municipal — City of Defiance ──────────────────────────────────
    {
        "site_id":          "DEF-S-006",
        "name":             "Fort Grounds",
        "category":         "Park",
        "subtype":          "Historic Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "The Fort Grounds occupy the site of Fort Defiance, erected by General Anthony Wayne in 1794 at the confluence of the Maumee and Auglaize Rivers during his campaign leading to the Battle of Fallen Timbers. Points in the sidewalk memorialize the corners of the fort. The grounds have been preserved for over a century since the city's incorporation. The Defiance Public Library (Carnegie Library) is also located on the grounds.",
        "location":         "320 Fort Street, Defiance, OH 43512; at the confluence of the Maumee and Auglaize Rivers",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2874974,
        "gps_lon":          -84.3572446,
        "gps_confidence":   "MED",
        "features":         "Hiking Trail;Bridge;Historic Marker;Picnic Area",
        "features_raw":     "Walking paths; bench swings overlooking the river; bridge over the river; historical marker sign; picnic areas with river views; Carnegie Library building on grounds",
        "notes":            "Fort Defiance (1794) is listed on the NRHP (listed 1980) — NRHP designation not in vocabulary constants; designation left blank. Also known as 'Fort Defiance Park' and 'Old Fort Defiance Park'. Adjacent to Pontiac Metro Park at same confluence — distinct sites. NCT/Buckeye Trail routes through or adjacent to this area.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Fort-Grounds-5",
        "urls":             "https://visitdefianceohio.com/explore/history/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-007",
        "name":             "Diehl Park",
        "category":         "Park",
        "subtype":          "Sports Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A large community park on the northwest side of Defiance featuring athletic fields and the Kids Creation Playground, a community-built playground from 2000. The park received updated playground equipment in 2017 and lighting upgrades for ball fields in 2001.",
        "location":         "909 Wemor Drive, Defiance, OH 43512; northwest side of the city",
        "acres":            39.77,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2982509,
        "gps_lon":          -84.3674670,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond;Pavilion;Playground;Basketball Court;Restrooms;Parking Lot;ADA Accessible",
        "features_raw":     "Four girls softball fields; one boys baseball field; two large covered shelter houses; Kids Creation Playground (community-built 2000); basketball court; restrooms; parking; ADA accessible",
        "notes":            "Kids Creation Playground (community-built 2000) is a named feature. Updated playground equipment 2017; lighting upgrades 2001.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Diehl-Park-3",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-008",
        "name":             "Kingsbury Riverfront Park, Pool, and Pickleball Facilities",
        "category":         "Park",
        "subtype":          "Waterfront Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A riverfront community park on the Auglaize River featuring a public pool, pickleball courts, and waterfront green space. The pool underwent a major $750,000 renovation beginning in 1999, adding a new water slide and expanded deck area.",
        "location":         "102 Auglaize Street, Defiance, OH 43512",
        "acres":            15.49,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2859503,
        "gps_lon":          -84.3559868,
        "gps_confidence":   "MED",
        "features":         "Swimming Pool;Waterslide;Restrooms;Pickleball Court;Parking Lot",
        "features_raw":     "Swimming pool (main pool max 5 ft depth; $3 admission; baby pool free for children 5 and under); water slide; locker rooms; restrooms; pickleball courts; parking; river access",
        "notes":            "DEF-F-01 RESOLVED: two baseline rows confirmed as single entity. 15.49 acres. Pool season: first week of June through mid-August. Formally 'Kingsbury Park'; full official name per city facilities page used here.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Kingsbury-Park-Pool-and-Pickleball-10",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-009",
        "name":             "Bronson Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "Defiance Public Library System",
        "coordination":     "Defiance Public Library System (StoryWalk program)",
        "description":      "A 25-acre multi-purpose community park that underwent significant renovations including new playground equipment, river swings, updated shelter houses, ADA-compliant sidewalks, and a new multi-use path connecting to Splash Park. The park hosts the StoryWalk Trail (Defiance Public Library program) and is adjacent to the Splash Park facility.",
        "location":         "2104 Power Dam Road, Defiance, OH 43512",
        "acres":            25.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2579920,
        "gps_lon":          -84.3906290,
        "gps_confidence":   "MED",
        "features":         "Volleyball Court;Ball Diamond;Pavilion;Basketball Court;Playground;ADA Accessible;Multi-use Trail",
        "features_raw":     "Two sand volleyball courts; two ball fields; three shelter houses; basketball court; playground; ADA-compliant sidewalks; multi-use path to Splash Park; river swings; 'Pockets of Play' interactive elements along path",
        "notes":            "DEF-F-07 RESOLVED: parent of Splash Park (DEF-S-010). Splash Park replaced former Bronson Pool (opened July 4, 2018). StoryWalk Trail (DEF-T-005) is a child trail. Power Dam Road named after Auglaize Hydro dam (Bryan Municipal Utilities) — park is NOT at the dam.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Bronson-Park-2",
        "urls":             "https://cityofdefiance.com/183/Bronson-Park;https://visitdefianceohio.com/business-directory/bronson-park/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-010",
        "name":             "Splash Park",
        "category":         "Recreation Facility",
        "subtype":          "",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "The Defiance Splash Park opened July 4, 2018, repurposing the former Bronson Pool facility into a free, ADA-compliant splash pad open to the public. The facility won 3rd place in the 2019 Ohio Parks and Recreation Association Capital Improvement Project category. Total project cost: $1.6 million. Open May 1 through October, 9 a.m. to 9 p.m.",
        "location":         "2104 Power Dam Road, Defiance, OH 43512 (within Bronson Park complex)",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2583791,
        "gps_lon":          -84.3901891,
        "gps_confidence":   "MED",
        "features":         "Spray Park;Playground;Picnic Area;Restrooms;ADA Accessible",
        "features_raw":     "Splash pad (water spray features); playground; picnic areas; tables; restrooms; ADA accessible; connected to Bronson Park via multi-use path",
        "notes":            "Child of Bronson Park (DEF-S-009). Replaced former Bronson Pool. Opened July 4, 2018; $1.6M project; 2019 OPRA award (3rd place, Capital Improvement). Connected to Bronson Park via walkway added 2021.",
        "url_primary":      "https://www.cityofdefiance.com/223/Splash-Park",
        "urls":             "",
        "parent_site_id":   "DEF-S-009",
    },
    {
        "site_id":          "DEF-S-011",
        "name":             "Canal Park",
        "category":         "Park",
        "subtype":          "Historic Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A public historic park featuring the partially renovated remains of the Miami and Erie Canal Lock No. 37, which survived the devastating 1913 floods. The north end of the lock structure was left exposed after the canal's decline and partially renovated in 1997. The site includes an adjacent amphitheater used for community events.",
        "location":         "310 Clinton Street (behind the building), Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2864106,
        "gps_lon":          -84.3630635,
        "gps_confidence":   "MED",
        "features":         "Amphitheater;Historic Lock",
        "features_raw":     "Amphitheater; Miami and Erie Canal Lock No. 37 remains (historic structure); open park area; free admission",
        "notes":            "Contains north end of Miami and Erie Canal Lock No. 37. Partially renovated 1997. Google Maps shows entity named 'Amphitheater' at this address rather than 'Canal Park'.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Canal-Park-40",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-012",
        "name":             "Eastside Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A neighborhood park revitalized as part of the Eastside Neighborhood Revitalization Project, featuring new playground equipment, athletic courts, and a shelter house. Formerly known as Compo Park.",
        "location":         "1185 Karnes Avenue, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2724894,
        "gps_lon":          -84.3535072,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond;Basketball Court;Playground;Pavilion;Picnic Area;Grill;Parking Lot;ADA Accessible",
        "features_raw":     "Baseball/softball diamond; basketball court; playground; picnic shelters; picnic tables; grill; lights; parking; ADA accessible",
        "notes":            "Formerly known as 'Compo Park.' Revitalized through Eastside Neighborhood Revitalization Project.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Eastside-Park-4",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-013",
        "name":             "Riverside Park",
        "category":         "Park",
        "subtype":          "Sports Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A 30-acre community park along the Maumee River featuring athletic fields including four soccer fields managed by the Optimist Club. Optimist Soccer fields were redesigned, regraded, and reseeded in 2021.",
        "location":         "849 Riverside Avenue, Defiance, OH 43512; along the Maumee River",
        "acres":            30.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2768669,
        "gps_lon":          -84.3616889,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond;Soccer Pitch;Playground;Pavilion;Picnic Area;Grill;Restrooms;Parking Lot",
        "features_raw":     "Baseball/softball diamond; four soccer fields; playground; picnic shelters; picnic tables; grill; restrooms; parking; Maumee River frontage",
        "notes":            "Soccer fields associated with Optimist Club program (redesigned 2021). Maumee River frontage noted.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Riverside-Park-13",
        "urls":             "https://visitdefianceohio.com/business-directory/riverside-park/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-014",
        "name":             "Reservoir and Disc Golf",
        "category":         "Park",
        "subtype":          "Greenspace",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A municipal recreation area centered on the City of Defiance upground water supply reservoir. Features a 9-hole disc golf course, a 1.25-mile stone walkway around the top of the reservoir, the Reservoir Nature Trail (boardwalk through north-side woods), a boat ramp and dock, and a sledding hill. The trail system connects to the Buckeye Trail / North Country NST along Canal Road.",
        "location":         "1261 Precision Way, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2707967,
        "gps_lon":          -84.3920288,
        "gps_confidence":   "MED",
        "features":         "Disc Golf Course;Hiking Trail;Parking Lot;Boat Ramp;Sledding Hill;Multi-use Trail;Canal Structure",
        "features_raw":     "9-hole disc golf course; 1.25-mile stone walkway around reservoir with 6 benches + bench at handicapped parking near boat ramp; 10-space stone parking lot; boat ramp; dock; sledding hill with lights (off Kibble Road); multi-use asphalt trail around reservoir (10 ft wide, completed 2015); historical Miami and Erie Canal section along Canal Road; connection to Buckeye Trail via Canal Road",
        "notes":            "NID seed 'Defiance Upground Reservoir (NID)' resolves to infrastructure, not separate entity. Reservoir Nature Trail (DEF-T-006) is child trail. Trail connects to Buckeye Trail/NCT along Canal Road. Bark & Run Dog Park (11795 Precision Way) is a separate T8 entity.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Reservoir-Disc-Golf-11",
        "urls":             "https://visitdefianceohio.com/business-directory/reservoir-and-disc-golf/;https://www.alltrails.com/trail/us/ohio/defiance-reservoir;https://ohio.org/wps/portal/gov/tourism/things-to-do/destinations/defiance-reservoir-walking-trails",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-015",
        "name":             "Palmer Park",
        "category":         "Park",
        "subtype":          "Sports Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A small community park near Defiance High School and the YMCA, featuring tennis courts and a playground area. Serves both the high school and the general public.",
        "location":         "1755 Palmer Drive, Defiance, OH 43512; near Defiance High School and the YMCA",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2657975,
        "gps_lon":          -84.3605872,
        "gps_confidence":   "MED",
        "features":         "Tennis Court;Playground",
        "features_raw":     "Five tennis courts; playground area",
        "notes":            "MINIMAL_DATA — acreage not documented.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Palmer-Park-41",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-016",
        "name":             "Pontiac Metro Park",
        "category":         "Park",
        "subtype":          "Waterfront Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio (ownership unconfirmed — see notes)",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A scenic riverside park with views of the Maumee and Auglaize rivers confluence, featuring in-town river access with a boat ramp. The park marks the site of the Old French Indian Apple Tree and the possible birthplace of Ottawa Chief Pontiac (1712). Features the Zonta Fountain, swings overlooking the rivers, a gazebo, and a monument to 2006 Indianapolis 500 champion Sam Hornish Jr. Hosts annual fireworks, car shows, boat shows, and war re-enactments.",
        "location":         "315 East River Road, Defiance, OH 43512; at the confluence of the Maumee and Auglaize Rivers",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2892403,
        "gps_lon":          -84.3574256,
        "gps_confidence":   "MED",
        "features":         "Boat Ramp;Parking Lot;Pavilion;Picnic Area;Hiking Trail;Fountain;Historic Marker;Monument;Gazebo",
        "features_raw":     "Boat launch; ample parking; pavilion; picnic areas; river swings; trails; Zonta Fountain; walkways; historical markers; Old French Indian Apple Tree Marker; Sam Hornish Jr. monument (2006 Indy 500 champion); gazebo",
        "notes":            "VERIFY_GOVERNANCE: City website states park is 'not a City-owned Park but lies within the City boundaries'; managed by City Parks & Rec per contact email cfeeney@cityofdefiance.gov. Ownership may be county or state — unresolved. DEF-F-02 RESOLVED: 'Metro Park' is a local name, NOT a metropark district affiliation. NCT/Buckeye Trail routes through this park. Adjacent to Fort Grounds (320 Fort St).",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Pontiac-Metro-Park-9",
        "urls":             "https://visitdefianceohio.com/business-directory/pontiac-metro-park/;https://www.midwestguest.com/2015/03/pontiac-metro-park-in-defiance-ohio-chief-pontiacs-birthplace.html",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-017",
        "name":             "William C. Holgate Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A neighborhood park in Defiance's historic district, formerly the site of the Second Ward School until the 1940s. Named William C. Holgate Park in memory of one of Defiance's most prominent early citizens (1994 designation). Features a Victorian gazebo and tree walk built by the Holgate Avenue Association in 1997. Received new playground equipment, new landscaping, renovated basketball court, and a new shelter house in Spring 2019.",
        "location":         "811 Holgate Avenue, Defiance, OH 43512; Holgate Avenue historic district",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2833452,
        "gps_lon":          -84.3732499,
        "gps_confidence":   "MED",
        "features":         "Playground;Basketball Court;Pavilion;Gazebo",
        "features_raw":     "Playground equipment; basketball court; picnic shelters; picnic tables; Victorian gazebo; power access; shelter house; landscaping; 'Healthy Body Healthy Mind' signage",
        "notes":            "Commonly 'Holgate Park.' Formerly site of Second Ward School (demolished 1940s). Named 1994. Victorian Gazebo + tree walk built by Holgate Avenue Association 1997. Renovated Spring 2019.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Holgate-Park-6",
        "urls":             "https://cityofdefiance.com/215/Holgate-Park;https://visitdefianceohio.com/business-directory/holgate-park/;https://www.hmdb.org/m.asp?m=173030",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-018",
        "name":             "Hometown Heroes Park",
        "category":         "Memorial",
        "subtype":          "Veterans Memorial",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "AMVETS Post 1991",
        "coordination":     "AMVETS Post 1991 (419-784-2356; 1795 Spruce Street, Defiance, OH)",
        "description":      "A memorial park established September 2013 as a lasting tribute to active duty men and women service members currently serving the country. Features recognition boards displaying the names of active duty personnel and flags honoring military service. A collaborative community effort coordinated with AMVETS Post 1991.",
        "location":         "648 Clinton Street, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Monument",
        "features_raw":     "Active duty service member recognition boards; flags; park signage",
        "notes":            "Established September 2013. No standalone Google Maps entity — address geocoded via Nominatim. Primarily a memorial installation (recognition boards + flags) rather than a traditional park.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Hometown-Heroes-Park-7",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-019",
        "name":             "Triangle Park",
        "category":         "Park",
        "subtype":          "Historic Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A small historic park featuring a clock tower, historically part of the Defiance City Schools property, donated by the Latty and Holgate families in the 1860s. Features trees, flowering vegetation, and open green space.",
        "location":         "655 Clinton Street, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2822475,
        "gps_lon":          -84.3650681,
        "gps_confidence":   "MED",
        "features":         "Historic Structure",
        "features_raw":     "Clock tower; trees and flowering vegetation; open park area",
        "notes":            "Very small park/triangle. Donated by Latty and Holgate families in 1860s. Clock tower is the defining feature. MINIMAL_DATA — acreage not documented.",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Triangle-Park-Clock-Tower",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-020",
        "name":             "Veteran's Memorial Park at Latty's Grove",
        "category":         "Memorial",
        "subtype":          "Veterans Memorial",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A historic park established as Latty's Grove in 1937 and officially designated Veteran's Memorial Grove in 1947, providing 'a fitting and appropriate background for commemoration of Defiance soldier's sacrifice in all wars.' The site has been visited by military figures including General Wayne (1794), General Winchester, William H. Harrison, and Colonel Richard Johnson. Continues to serve as a gathering place for family reunions and outdoor events.",
        "location":         "610 Williams Street, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2794674,
        "gps_lon":          -84.3673302,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond;Basketball Court;Tennis Court;Playground;Pavilion;Picnic Area;Parking Lot",
        "features_raw":     "Baseball/softball diamond; basketball court; tennis court; playground (updated 2014); Latty's Grove Shelter Houses 2 and 3; picnic tables; parking",
        "notes":            "Established 1937 as 'Latty's Grove'; designated 'Veteran's Memorial Grove' 1947. Playground updated summer 2014. Two overlapping Google Maps entities at this location: 'Veteran's Memorial Park' and 'Latty Grove Park' (~70m apart). Primary GPS from 'Latty Grove Park' entity (606 Williams St address on Maps).",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Veterans-Memorial-Park-at-Lattys-Grove-16",
        "urls":             "https://visitdefianceohio.com/business-directory/veterans-memorial-park-at-lattys-grove/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-021",
        "name":             "Buchman Park on the Glaize",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A City of Defiance neighborhood park on the Auglaize River (Glaize), discovered during T6 map verification pass. Not found in web discovery phase.",
        "location":         "314 Auglaize St, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2836971,
        "gps_lon":          -84.3563774,
        "gps_confidence":   "MED",
        "features":         "",
        "features_raw":     "",
        "notes":            "MAP_VERIFICATION_FIND. Found during §4.4 Google Maps pass. Confirmed City of Defiance (cityofdefiance.com, (419) 784-2745). MINIMAL_DATA — requires confirmation against city parks list.",
        "url_primary":      "https://www.cityofdefiance.com/216/Parks-Recreation",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-022",
        "name":             "Memory Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "City of Defiance, Ohio",
        "governance":       "City of Defiance, Parks & Recreation",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A small City of Defiance park on 5th Street, described as a 'great green space' in the single Google Maps review. Discovered during T6 map verification pass.",
        "location":         "5th St, Defiance, OH 43512",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2830331,
        "gps_lon":          -84.3616312,
        "gps_confidence":   "MED",
        "features":         "",
        "features_raw":     "Green space",
        "notes":            "MAP_VERIFICATION_FIND. Only 1 Google Maps review ('Great green space'). No phone, hours, or website on Maps. MINIMAL_DATA — requires confirmation against city parks list. Possibly a small memorial/pocket park.",
        "url_primary":      "https://www.cityofdefiance.com/216/Parks-Recreation",
        "urls":             "",
        "parent_site_id":   "",
    },

    # ── Tier 6: Municipal — Villages ──────────────────────────────────────────
    {
        "site_id":          "DEF-S-023",
        "name":             "Hicksville Community Park",
        "category":         "Park",
        "subtype":          "Sports Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Hicksville, Ohio",
        "governance":       "Village of Hicksville, Parks & Recreation Department",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "The main village park complex in Hicksville, featuring extensive athletic and recreational facilities. A new splash pad opened approximately summer 2024, replacing the aging pool facility (pool closed 2023 while new facility under construction).",
        "location":         "598 N Bryan Street, Hicksville, OH 43526",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2966175,
        "gps_lon":          -84.7727043,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond;Basketball Court;Disc Golf Course;Playground;Skate Park;Sledding Hill;Soccer Pitch;Tennis Court;Volleyball Court;Pavilion;Spray Park",
        "features_raw":     "Ball diamonds (multiple); basketball courts; disc golf course; playground; skate park; sledding hill; soccer field; tennis courts; track; volleyball courts; Rotary Pavilion (year-round rental, $150 deposit + $110/day); open pavilions (no rental fee); splash pad (opened ~2024)",
        "notes":            "Baseline seeds 'Hicksville Community Park and Pool' and 'Rotary Park (Hicksville)' are the SAME entity. 'Rotary Park' is an informal name (contains Rotary Pavilion). Pool closed 2023; splash pad opened ~2024. ADDRESS_DISCREPANCY: admin address 111 S Main St vs GPS at 598 N Bryan St; using GPS address. Reservations: Rotary Pavilion (419) 542-8224.",
        "url_primary":      "https://villageofhicksville.com/parks-and-recreation/",
        "urls":             "https://villageofhicksville.com/park-facilities/;https://hicksvilleohiochamber.org/visit-hicksville/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-024",
        "name":             "Froggy Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Hicksville, Ohio",
        "governance":       "Village of Hicksville",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "",
        "location":         "547 N Main Street, Hicksville, OH 43526",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2970155,
        "gps_lon":          -84.7687773,
        "gps_confidence":   "MED",
        "features":         "",
        "features_raw":     "",
        "notes":            "MINIMAL_DATA. Address 547 N Main St from OhioBiz directory. Listed as Area Recreation site by Hicksville Chamber. Distinct from Hicksville Community Park (598 N Bryan St).",
        "url_primary":      "https://www.ohiobiz.com/listings/froggy-park",
        "urls":             "https://hicksvilleohiochamber.org/visit-hicksville/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-025",
        "name":             "Hicksville Veterans Memorial",
        "category":         "Memorial",
        "subtype":          "Veterans Memorial",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Hicksville, Ohio",
        "governance":       "Village of Hicksville",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A community memorial park honoring men and women who have served the United States of America to preserve our rights.",
        "location":         "Hicksville, OH 43526 (address not confirmed from authoritative source)",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2943616,
        "gps_lon":          -84.7682625,
        "gps_confidence":   "MED",
        "features":         "",
        "features_raw":     "",
        "notes":            "MINIMAL_DATA. VERIFY_ADDRESS — address not confirmed. Distinct from 'First Church of Christ Veterans Memorial' (118 N Main St), which is a church memorial. Village contact: (419) 542-6138.",
        "url_primary":      "https://www.facebook.com/HicksvilleVeteransMemorial/",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-026",
        "name":             "Little Reservation Station Park",
        "category":         "Park",
        "subtype":          "Historic Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Sherwood, Ohio",
        "governance":       "Village of Sherwood",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A park where residents can enjoy peaceful moments in the Northwest Ohio outdoors, paying homage to the railroads that first brought settlers to Sherwood approximately 150 years ago.",
        "location":         "Sherwood, OH 43556 (address not confirmed from authoritative source)",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2896819,
        "gps_lon":          -84.5525676,
        "gps_confidence":   "MED",
        "features":         "",
        "features_raw":     "",
        "notes":            "MINIMAL_DATA. Railroad heritage park per village government website (TLS error prevented page fetch; description from search snippet). Address not confirmed. Village of Sherwood: 200 N Harrison St, (419) 899-2145.",
        "url_primary":      "http://www.sherwoodohio.villagegovt.org/Default.aspx?tabid=5688",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-027",
        "name":             "Moats Park",
        "category":         "Park",
        "subtype":          "Sports Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Sherwood, Ohio",
        "governance":       "Village of Sherwood",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "A community park and ball field in the Village of Sherwood. Discovered during T6 map verification pass; not found in web discovery phase.",
        "location":         "210 Cedar St, Sherwood, OH 43556",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.2827831,
        "gps_lon":          -84.5528207,
        "gps_confidence":   "MED",
        "features":         "Ball Diamond",
        "features_raw":     "Ball field; park",
        "notes":            "MAP_VERIFICATION_FIND (4.1 rating, 37 reviews). 'Sherwood Ball Park' appears as a possible separate Google Maps entity nearby — may be alternate name or second facility; recommend verification.",
        "url_primary":      "http://www.sherwoodohio.villagegovt.org/",
        "urls":             "",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-028",
        "name":             "Ney Park",
        "category":         "Park",
        "subtype":          "Neighborhood Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Village of Ney, Ohio",
        "governance":       "Village of Ney",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "The Village of Ney's main community park, providing facilities and programs for local residents and visitors with sports facilities, nature areas, and a playground.",
        "location":         "370 W Main St, Ney, OH 43549",
        "acres":            None,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          41.3811614,
        "gps_lon":          -84.5250569,
        "gps_confidence":   "MED",
        "features":         "Playground",
        "features_raw":     "Sports facilities; nature areas; playground",
        "notes":            "MINIMAL_DATA. Google Maps shows entity 'Ney Splash Pad' at 370 W Main St — GPS from this entity. Park may be primarily known for splash pad on Maps. Contact: Sheila Bostater (419-392-5218), Park Reservations (419-658-2578).",
        "url_primary":      "https://villageofney.com/parks-and-recreation",
        "urls":             "",
        "parent_site_id":   "",
    },

    # ── Tier 7: Conservancy / Land Trust ─────────────────────────────────────
    {
        "site_id":          "DEF-S-029",
        "name":             "Thoreau Wildlife Reserve",
        "category":         "Nature Preserve",
        "subtype":          "Private Nature Preserve",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Diehl Family Foundation",
        "governance":       "Diehl Family Foundation",
        "partner_agencies": "National Audubon Society (Audubon Sanctuary Program)",
        "coordination":     "",
        "description":      "250-acre wildlife reserve encompassing various ecosystems including wetlands, prairie, hardwood forest, and old growth forest. Launched by the Diehl Family Foundation in 1989 as a land restoration initiative; opened to public in 2020. Located along Haller Road near Nobel Elementary School. Features interpretive signage with quotations from naturalist H.D. Thoreau. An Audubon Sanctuary Program partner supporting nesting bluebirds, wood ducks, and mallard ducks. Visitors enter via gravel lane to parking area. Seasonal restroom facility (March–November) near parking lot; nature center by Walden Pond currently unavailable.",
        "location":         "10485 Haller Road, Defiance, OH 43512",
        "acres":            250.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Hiking Trail;Wetland;Prairie;Parking Lot;Restrooms;Interpretive Sign",
        "features_raw":     "4 nature trails (2 miles total); wetlands; prairie; hardwood forest; old growth forest; gravel parking lot; seasonal restroom (March–November); interpretive Thoreau quote signage; Audubon Sanctuary bluebird/wood duck/mallard nesting program; leash-required dog access; foot traffic only",
        "notes":            "Diehl Family Foundation EIN 47-5650292. Open dawn-dusk since 2020. 4 trails (2 mi total) — trail names not published. Nature center by Walden Pond currently unavailable. Leash required.",
        "url_primary":      "https://www.thoreauwildlifereserve.org/",
        "urls":             "https://www.thoreauwildlifereserve.org/visit;https://visitdefianceohio.com/thoreau/;https://visitdefianceohio.com/business-directory/thoreau-wildlife-reserve-2/",
        "parent_site_id":   "",
    },

    # ── Tier 8: Private ───────────────────────────────────────────────────────
    {
        "site_id":          "DEF-S-030",
        "name":             "Camp Lakota / Camp Neil Armstrong",
        "category":         "Campground",
        "subtype":          "Group Campground",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Black Swamp Area Council, Boy Scouts of America",
        "governance":       "Black Swamp Area Council, BSA",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "640-acre Boy Scout camp encompassing diverse forested terrain, the 48-acre Lake Glengary, and bordered on the west by the Auglaize River. Established in 1941; considered by many to provide a 'rustic' summer camp experience. Known for the connection to Neil Armstrong, who attended the camp as a boy and later served on staff. Offers Scouts BSA summer programming, weekend camping for packs and troops, advancement training, and outdoor skill development. Located south of the City of Defiance.",
        "location":         "2180 Ginter Road, Defiance, OH 43512",
        "acres":            640.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Camping;Lake;Hiking Trail;Watercraft Access",
        "features_raw":     "640 acres; 48-acre Lake Glengary; Auglaize River (west border); 14 conservation-style campsites (9 Lakota side + 5 Neil Armstrong side); aquatic activities; hiking; canoeing; program areas around lake; capacity 175–200 Scouts per week during summer camp",
        "notes":            "Limited access: restricted to Scouts BSA members and registered groups. BSA website referenced 'Hancock County' in text but address ZIP 43512 and USGS station (USGS-411502084225000 'Camp Lakota Bsa LK NR Defiance OH') confirm Defiance County. Camp Lakota Boy Scout Lake Dam is NID infrastructure — not a separate entity. Neil Armstrong connection noted.",
        "url_primary":      "https://www.blackswampbsa.org/camping/camp-lakota/63303",
        "urls":             "https://www.facebook.com/CampLakotaScoutingAmerica/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-031",
        "name":             "Bark & Run Dog Park",
        "category":         "Park",
        "subtype":          "Dog Park",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Defiance Bark'n Runners (501c3 nonprofit)",
        "governance":       "Defiance Bark'n Runners",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "501c3 nonprofit-operated membership dog park comprising two one-acre fenced areas where small and large dogs can be separated for safer play. Not affiliated with the City of Defiance. Funded through memberships and donations. Located on Precision Way across from the Defiance City Reservoir.",
        "location":         "11795 Precision Way, Defiance, OH 43512",
        "acres":            2.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Dog Park;Pavilion",
        "features_raw":     "Two 1-acre fenced areas (small dog + large dog separation); shade trees; shelter house; benches; pet waste bag dispensers; membership required ($45 first dog, $10 each additional)",
        "notes":            "Membership required (annual June–June); children under 12 not permitted. City website lists under Facilities despite 'not affiliated with city' statement. NOTE: City may own land and lease to nonprofit — verify parcel at 11795 Precision Way (affects tier assignment).",
        "url_primary":      "https://www.defiancebarkandrun.com/",
        "urls":             "https://cityofdefiance.com/Facilities/Facility/Details/Bark-Run-Dog-Park-1;https://www.facebook.com/barknrun/",
        "parent_site_id":   "",
    },
    {
        "site_id":          "DEF-S-032",
        "name":             "Shallow Creek Hunting Preserve",
        "category":         "Hunting Area",
        "subtype":          "",
        "designation":      "",
        "status":           "Active",
        "ownership":        "Private",
        "governance":       "Private",
        "partner_agencies": "",
        "coordination":     "",
        "description":      "Private ODNR-licensed hunting preserve offering morning and afternoon pheasant hunts in 40-acre grassland fields. Fee-based public access (hunting reservation required). Contact 419-784-3911 to schedule a hunt.",
        "location":         "7599 Stever Road, Defiance, OH 43512",
        "acres":            40.0,
        "counties":         "Defiance",
        "municipality":     "",
        "township":         "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
        "features":         "Hunting Area",
        "features_raw":     "40-acre grassland fields; pheasant hunting (morning + afternoon sessions); fee-based reservation hunting; ODNR licensed hunting preserve",
        "notes":            "ODNR-licensed hunting preserve. Fee-based limited access (reservation required). ODNR license number not found in available sources.",
        "url_primary":      "https://www.facebook.com/shallowcreekhuntingpreserve/",
        "urls":             "https://www.finandfield.com/organizations/shallow-creek-hunting-preserve-defiance",
        "parent_site_id":   "",
    },
]

TRAILS = [
    # ── Tier 1: Federal ───────────────────────────────────────────────────────
    {
        "trail_id":         "DEF-T-001",
        "name":             "North Country National Scenic Trail",
        "alternate_names":  "NCT; Buckeye Trail (co-route in Ohio)",
        "use_type":         "Hiking",
        "surface_type":     "Mixed",
        "origin_type":      "Historic Route",
        "length_mi":        None,
        "counties":         "Defiance; Henry; Lucas; Paulding",
        "governance":       "National Park Service",
        "partner_agencies": "North Country Trail Association; Buckeye Trail Association",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "The longest trail in the National Trails System, the North Country National Scenic Trail stretches approximately 4,800 miles across eight states from North Dakota to Vermont. In Ohio, the trail joins and shares the route of the Buckeye Trail for approximately 90% of its ~1,076-mile Ohio course, following canal towpaths, river corridors, and historic routes through northwest and central Ohio.",
        "trail_history":    "",
        "identity_notes":   "In Ohio, the NCT is co-routed with the Buckeye Trail (BTA) for ~90% of Ohio mileage. Within Defiance County: enters Defiance city, follows sidewalk, crosses Maumee River, routes through Pontiac Park, continues through Independence Dam State Park along the old Miami and Erie Canal towpath past Lock 13 ruins. 'Defiance Section' (55 miles across Paulding, Defiance, Henry, Lucas Counties) is a BTA section designation — not an NCT-specific named segment. Multi-county, multi-state; record captures Defiance County presence.",
        "notes":            "",
        "url_primary":      "https://www.nps.gov/noco/index.htm",
        "maps":             "https://northcountrytrail.org/the-trail/ohio/;https://buckeyetrail.org/sections/sections-map.php?section=defiance",
        "parent_site_id":   "",
    },

    # ── Tier 2: State ─────────────────────────────────────────────────────────
    {
        "trail_id":         "DEF-T-002",
        "name":             "Maumee River Water Trail",
        "alternate_names":  "",
        "use_type":         "Water",
        "surface_type":     "Water",
        "origin_type":      "Other",
        "length_mi":        107.0,
        "counties":         "Defiance; Henry; Lucas; Paulding; Wood",
        "governance":       "Ohio Department of Natural Resources; Metroparks Toledo",
        "partner_agencies": "Maumee Valley Planning Organization; Defiance Soil and Water Conservation District",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "A 107-mile water trail along the Maumee River from Maumee Bay and Lake Erie to the Ohio-Indiana border, connecting five Metroparks, three state parks (including Independence Dam State Park), three wildlife areas, and 15 other public parks at 39 access locations across Paulding, Defiance, Henry, Wood, and Lucas counties.",
        "trail_history":    "The Maumee River was designated an Ohio State Scenic River on July 18, 1974: scenic section = Ohio/Indiana state line to Defiance (43 river miles); recreational section = Defiance downstream to Maumee/Perrysburg Bridge (53 river miles). The Maumee River Water Trail branded route is distinct from the scenic river regulatory designation but substantially overlaps it.",
        "identity_notes":   "107 miles total; Defiance County is one of 5 counties. Independence Dam State Park is a named access point and suggested trip starting point. Managed cooperatively by ODNR and Metroparks Toledo.",
        "notes":            "",
        "url_primary":      "https://metroparkstoledo.com/features-and-rentals/maumee-river-water-trail/",
        "maps":             "https://metroparkstoledo.com/media/3621/maumee-waterway-brochure-031318-web.pdf;https://storymaps.arcgis.com/stories/ba766ce42e2b42e1ba7dca6859b1e7f4",
        "parent_site_id":   "",
    },
    {
        "trail_id":         "DEF-T-003",
        "name":             "Miami and Erie Canal Towpath Trail",
        "alternate_names":  "Independence Dam Hiking Trail",
        "use_type":         "Multi-Use",
        "surface_type":     "Natural Surface",
        "origin_type":      "Canal Towpath",
        "length_mi":        3.0,
        "counties":         "Defiance",
        "governance":       "Ohio Department of Natural Resources, Division of Parks and Watercraft",
        "partner_agencies": "",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "Three-mile trail following the historic towpath of the Miami and Erie Canal, meanders between the old canal and the Maumee River through a dense hardwood forest within Independence Dam State Park, ending at the village of Florida, Ohio. The trail passes the ruins of Lock Number 13 of the Miami and Erie Canal.",
        "trail_history":    "Former towpath of the Miami and Erie Canal; historically significant as a transportation route. Buckeye Trail and North Country NST route along this towpath through Independence Dam State Park.",
        "identity_notes":   "No single authoritative canonical name confirmed; 'Miami and Erie Canal Towpath Trail' is the descriptive name used. Source uses 'hiking trail, once the towpath of the Miami and Erie Canal.' Coordination: Buckeye Trail Association (co-routes through park).",
        "notes":            "36-mile bike loop referenced for marina area may extend beyond this 3-mile trail — scope requires verification.",
        "url_primary":      "https://www.stateparks.com/independence_dam_state_park_in_ohio.html",
        "maps":             "https://en.wikipedia.org/wiki/Independence_Dam_State_Park",
        "parent_site_id":   "DEF-S-001",
    },

    # ── Tier 3: District (SWCD) ───────────────────────────────────────────────
    {
        "trail_id":         "DEF-T-004",
        "name":             "Storybook Trail",
        "alternate_names":  "",
        "use_type":         "Hiking",
        "surface_type":     "Natural Surface",
        "origin_type":      "Purpose-Built",
        "length_mi":        0.5,
        "counties":         "Defiance",
        "governance":       "Defiance Soil and Water Conservation District",
        "partner_agencies": "",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "A seasonal storybook trail approximately half a mile long featuring a 15-page children's book that changes seasonally; visitors can enter a drawing to win copies of the featured book.",
        "trail_history":    "",
        "identity_notes":   "One of 5 trails at Penney Nature Center (total 3.5 miles). Only named trail confirmed from authoritative source. Remaining 4 trails are unnamed in available sources.",
        "notes":            "Seasonal operation. Distinct from StoryWalk Trail (DEF-T-005) at Bronson Park — different sites, different governance.",
        "url_primary":      "https://www.defianceswcd.org/penney-nature-center.html",
        "maps":             "",
        "parent_site_id":   "DEF-S-004",
    },

    # ── Tier 6: Municipal — City of Defiance ──────────────────────────────────
    {
        "trail_id":         "DEF-T-005",
        "name":             "StoryWalk Trail",
        "alternate_names":  "",
        "use_type":         "Hiking",
        "surface_type":     "Natural Surface",
        "origin_type":      "Purpose-Built",
        "length_mi":        None,
        "counties":         "Defiance",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "Defiance Public Library System",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "An outdoor StoryWalk trail at Bronson Park where pages of a picture book are displayed along a walking path for pedestrians to read as they move. By the end of the path the walker has read the book in its entirety. The book displayed changes seasonally; program facilitated by the Defiance Public Library.",
        "trail_history":    "",
        "identity_notes":   "Trail is within Bronson Park; facilitated by Defiance Public Library (seasonal program). Distinct from Storybook Trail (DEF-T-004) at Penney Nature Center (Tier 3 / SWCD). No length documented in authoritative source.",
        "notes":            "MINIMAL_DATA — exact trail length unknown. Host location possibly along existing park path.",
        "url_primary":      "https://defiancelibrary.org/event-location/bronson-park/",
        "maps":             "",
        "parent_site_id":   "DEF-S-009",
    },
    {
        "trail_id":         "DEF-T-006",
        "name":             "Reservoir Nature Trail",
        "alternate_names":  "Defiance Reservoir Trail",
        "use_type":         "Multi-Use",
        "surface_type":     "Mixed",
        "origin_type":      "Purpose-Built",
        "length_mi":        0.57,
        "counties":         "Defiance",
        "governance":       "City of Defiance, Parks & Recreation Department",
        "partner_agencies": "",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "Wheelchair accessible; ADA compliant (8 ft wide multi-use pathway)",
        "description":      "A boardwalk-style trail in the wooded area north of the Defiance municipal reservoir, approximately 2,500 feet of boardwalk through woods plus 500 feet of asphalt from the parking lot to the woods. Eight feet wide, creating a multi-use wheelchair-accessible pathway around the north side of the reservoir. Supports bird watching and nature walks; connects to the Buckeye Trail / North Country NST along Canal Road, forming a non-motorized accessible loop around the municipal reservoir.",
        "trail_history":    "",
        "identity_notes":   "DEF-F-08 RESOLVED: Confirmed as child trail of Reservoir and Disc Golf (DEF-S-014). Trail connects to Buckeye Trail/NCT along Canal Road — cross-tier linkage. Length: ~2,500 ft boardwalk + ~500 ft asphalt (total ~3,000 ft / ~0.57 mi).",
        "notes":            "",
        "url_primary":      "https://cityofdefiance.com/Facilities/Facility/Details/Reservoir-Nature-Trail-12",
        "maps":             "https://www.alltrails.com/trail/us/ohio/defiance-reservoir;https://ohio.org/wps/portal/gov/tourism/things-to-do/destinations/defiance-reservoir-walking-trails",
        "parent_site_id":   "DEF-S-014",
        "gps_lat":          41.2690967,
        "gps_lon":          -84.3993561,
        "gps_confidence":   "MED",
    },

    # ── Tier 7: Conservancy ───────────────────────────────────────────────────
    {
        "trail_id":         "DEF-T-007",
        "name":             "Hicksville Nature Trail",
        "alternate_names":  "",
        "use_type":         "Hiking",
        "surface_type":     "Natural Surface",
        "origin_type":      "Purpose-Built",
        "length_mi":        1.8,
        "counties":         "Defiance",
        "governance":       "Hicksville Trail Association",
        "partner_agencies": "",
        "status":           "Active",
        "difficulty":       "",
        "accessibility":    "",
        "description":      "Beautiful community nature trail, 1.8 mile loop.",
        "trail_history":    "",
        "identity_notes":   "GOVERNANCE_UNCERTAIN: Hicksville Trail Association governance not confirmed. No IRS nonprofit registration found. May be on private land under license/agreement or county land under maintenance agreement. Rural location outside Hicksville village limits. Verify parcel owner at 9425 Casebeer Miller Rd.",
        "notes":            "GOVERNANCE_UNCERTAIN flag. Trail features meadow of wildflowers and wooded portions.",
        "url_primary":      "https://visitdefianceohio.com/business-directory/hicksville-nature-trail/",
        "maps":             "https://www.facebook.com/HicksvilleTrailAssociation/",
        "parent_site_id":   "",
        "gps_lat":          None,
        "gps_lon":          None,
        "gps_confidence":   "NONE",
    },
]

TRAIL_SEGMENTS = []
TRAIL_NETWORKS = []
SITE_NETWORKS  = []

ACCESS_POINTS = [
    # ── Tier 2: State ─────────────────────────────────────────────────────────
    {
        "access_point_id":    "DEF-AP-001",
        "name":               "Independence Dam State Park Boat Launch",
        "ap_type":            "Boat Ramp",
        "status":             "Active",
        "parent_entity_type": "Site",
        "parent_entity_id":   "DEF-S-001",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "27722 County Rd 424 / US Route 424 East, Defiance, Ohio; along Maumee River",
        "gps_lat":            None,
        "gps_lon":            None,
        "gps_confidence":     "NONE",
        "features":           "4-lane boat launch ramp; marina; hand-launch area",
        "identity_notes":     "Primary river access for Maumee River Water Trail in the Independence Dam SP segment. NCT/Buckeye Trail trailhead also located at or near this site. Hand-launch is a separate primitive access in the campground.",
        "notes":              "",
        "url_primary":        "https://www.stateparks.com/independence_dam_state_park_in_ohio.html",
    },
    {
        "access_point_id":    "DEF-AP-002",
        "name":               "Bend Road Bridge",
        "ap_type":            "River Access",
        "status":             "Active",
        "parent_entity_type": "",
        "parent_entity_id":   "",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "Near Sherwood, Defiance County, Ohio; Maumee River",
        "gps_lat":            None,
        "gps_lon":            None,
        "gps_confidence":     "NONE",
        "features":           "",
        "identity_notes":     "State DNR access site on the Maumee River near Sherwood. Part of the Maumee River Water Trail 39-point access network.",
        "notes":              "MINIMAL_DATA — GPS and facilities require verification.",
        "url_primary":        "https://visitdefianceohio.com/explore/fishing-boating/",
    },
    {
        "access_point_id":    "DEF-AP-003",
        "name":               "Five-Mile Creek Access Area",
        "ap_type":            "Boat Ramp",
        "status":             "Active",
        "parent_entity_type": "",
        "parent_entity_id":   "",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "Ohio State Route 111, southwest of Defiance, Ohio; Auglaize River",
        "gps_lat":            None,
        "gps_lon":            None,
        "gps_confidence":     "NONE",
        "features":           "Boat ramp",
        "identity_notes":     "ODNR Division of Wildlife public boat ramp on Auglaize River, OH-111 SW of Defiance. Second access possibly at County Highway 196/OH-637 bridge — may be same access area or separate ramp; needs field verification.",
        "notes":              "MINIMAL_DATA flag.",
        "url_primary":        "https://visitdefianceohio.com/explore/fishing-boating/",
    },

    # ── Tier 3: District (SWCD) ───────────────────────────────────────────────
    {
        "access_point_id":    "DEF-AP-004",
        "name":               "Penney Nature Center Trailhead",
        "ap_type":            "Trailhead",
        "status":             "Active",
        "parent_entity_type": "Site",
        "parent_entity_id":   "DEF-S-004",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "08855 Ashpacher Road, Defiance, OH 43512; entrance off Ashpacher Road",
        "gps_lat":            None,
        "gps_lon":            None,
        "gps_confidence":     "NONE",
        "features":           "Parking lot; trailhead sign with site map; pavilion",
        "identity_notes":     "Main entrance and parking area for Penney Nature Center. Improved parking lot completed recently.",
        "notes":              "MINIMAL_DATA — GPS requires verification. GPS propagated from parent site.",
        "url_primary":        "https://www.defianceswcd.org/penney-nature-center.html",
    },

    # ── Tier 6: Municipal — City of Defiance ──────────────────────────────────
    {
        "access_point_id":    "DEF-AP-005",
        "name":               "Pontiac Metro Park Boat Launch",
        "ap_type":            "Boat Ramp",
        "status":             "Active",
        "parent_entity_type": "Site",
        "parent_entity_id":   "DEF-S-016",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "315 East River Road, Defiance, OH 43512; Maumee River at Maumee/Auglaize confluence",
        "gps_lat":            41.2893480,
        "gps_lon":            -84.3552717,
        "gps_confidence":     "MED",
        "features":           "Boat ramp; ample parking; gazebo near ramp",
        "identity_notes":     "Primary in-town river access for Maumee River Water Trail in the Defiance city reach. NCT/Buckeye Trail passes through Pontiac Metro Park — de facto trail access point for NCT. VERIFY_GOVERNANCE flag carried from parent site.",
        "notes":              "",
        "url_primary":        "https://cityofdefiance.com/Facilities/Facility/Details/Pontiac-Metro-Park-9",
    },
    {
        "access_point_id":    "DEF-AP-006",
        "name":               "Reservoir Boat Ramp and Dock",
        "ap_type":            "Boat Ramp",
        "status":             "Active",
        "parent_entity_type": "Site",
        "parent_entity_id":   "DEF-S-014",
        "county":             "Defiance",
        "township":           "",
        "municipality":       "",
        "address":            "1261 Precision Way, Defiance, OH 43512; Defiance municipal reservoir",
        "gps_lat":            41.2687580,
        "gps_lon":            -84.3979906,
        "gps_confidence":     "MED",
        "features":           "Boat ramp; dock; 10-space stone parking lot; handicapped parking with bench",
        "identity_notes":     "Boat ramp and dock on Defiance municipal upground reservoir. AUTHORITY_FLAG: Google Maps links this entity to ohiodnr.gov — ODNR may manage or co-manage this boat launch. Possible overlap with T2 State (ODNR Division of Watercraft public boat ramp program).",
        "notes":              "Governance authority unresolved — may warrant reclassification to T2 or dual-governance note.",
        "url_primary":        "https://cityofdefiance.com/Facilities/Facility/Details/Reservoir-Disc-Golf-11",
    },
]

# ── GPS Acquisition Config ────────────────────────────────────────────────────

GPS_QUERIES = {
    # Sites needing Nominatim geocoding
    "DEF-S-001": "Independence Dam State Park, 27722 County Road 424, Defiance, Ohio",
    "DEF-S-002": "Oxbow Lake Wildlife Area, Defiance County, Ohio",
    "DEF-S-004": "08855 Ashpacher Road, Defiance, OH 43512",
    "DEF-S-005": "12296 Krouse Road, Defiance, OH 43512",
    "DEF-S-018": "648 Clinton Street, Defiance, OH 43512",
    "DEF-S-029": "10485 Haller Road, Defiance, OH 43512",
    "DEF-S-030": "2180 Ginter Road, Defiance, OH 43512",
    "DEF-S-031": "11795 Precision Way, Defiance, OH 43512",
    "DEF-S-032": "7599 Stever Road, Defiance, OH 43512",
    # Trails needing GPS
    "DEF-T-007": "9425 Casebeer Miller Road, Hicksville, Ohio",
    # Access points needing GPS (DEF-AP-001 uses fallback; no Nominatim query)
    "DEF-AP-002": "Bend Road, Maumee River, near Sherwood, Ohio",
    "DEF-AP-003": "State Route 111, Defiance, Ohio",
}

# Manual fallback coordinates for entities that may not geocode via Nominatim
GPS_FALLBACKS = {
    # Independence Dam State Park approximate centroid (~3 mi E of Defiance on Maumee R.)
    "DEF-S-001": (41.268000, -84.311000),
    # Oxbow Lake Wildlife Area approximate centroid (near NW Defiance County)
    "DEF-S-002": (41.330000, -84.395000),
    # Penney Nature Center — Ashpacher Rd, Defiance County (LOW; geocode failed)
    "DEF-S-004": (41.225000, -84.360000),
    # Thoreau Wildlife Reserve — Haller Rd near Nobel Elem., City of Defiance area (LOW)
    "DEF-S-029": (41.280000, -84.410000),
    # Independence Dam SP Boat Launch — same address as park (LOW; Nominatim unreliable)
    "DEF-AP-001": (41.268000, -84.311000),
    # Bend Road Bridge near Sherwood/Maumee River
    "DEF-AP-002": (41.296000, -84.555000),
    # Five-Mile Creek / OH-111 approximate
    "DEF-AP-003": (41.245000, -84.430000),
}

GPS_FALLBACK_CONF = {
    "DEF-S-001": "LOW",
    "DEF-S-002": "LOW",
    "DEF-S-004": "LOW",
    "DEF-S-029": "LOW",
    "DEF-AP-001": "LOW",
    "DEF-AP-002": "LOW",
    "DEF-AP-003": "LOW",
}


# ════════════════════════════════════════════════════════════════════════════════
#  MAIN — Pipeline execution
# ════════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Defiance County, Ohio — NAP Pipeline (defiance_oh_2026_04_19)")
    parser.add_argument("--db", default=DEFAULT_DB,
                        help="Path to SQLite database")
    parser.add_argument("--dry-run", action="store_true",
                        help="Write TSVs but do not modify database")
    args = parser.parse_args()

    print("=" * 60)
    print(f"Defiance County OH — NAP Pipeline  ({RUN_ID})")
    print(f"DB:      {args.db}")
    print(f"Dry run: {args.dry_run}")
    print("=" * 60)

    # ── Stage 2: Normalization complete (hardcoded above) ────────────────────
    print("\n[Stage 2] Normalization — complete "
          f"({len(SITES)} Sites, {len(TRAILS)} Trails, {len(ACCESS_POINTS)} APs)")

    # Ensure all entities have required defaults
    for s in SITES:
        s.setdefault("created_at", NOW)
        s.setdefault("updated_at", NOW)
        s.setdefault("plus_code", "")
        s.setdefault("municipality", "")
        s.setdefault("township", "")
    for t in TRAILS:
        t.setdefault("created_at", NOW)
        t.setdefault("updated_at", NOW)
        t.setdefault("gps_lat", None)
        t.setdefault("gps_lon", None)
        t.setdefault("gps_confidence", "NONE")
    for ap in ACCESS_POINTS:
        ap.setdefault("created_at", NOW)
        ap.setdefault("updated_at", NOW)
        ap.setdefault("plus_code", "")

    # ── Stage 3: GPS Acquisition ─────────────────────────────────────────────
    print("\n[Stage 3] GPS Acquisition")

    acquire_gps(SITES, "site_id", GPS_QUERIES, GPS_FALLBACKS, GPS_FALLBACK_CONF)
    acquire_gps(TRAILS, "trail_id", GPS_QUERIES, {})
    acquire_gps(ACCESS_POINTS, "access_point_id", GPS_QUERIES, GPS_FALLBACKS, GPS_FALLBACK_CONF)

    # Propagate GPS from parents
    propagate_gps_to_children(SITES)          # e.g. DEF-S-003 ← DEF-S-001
    propagate_gps_to_trails(TRAILS, SITES)    # e.g. DEF-T-003 ← DEF-S-001
    propagate_gps_to_aps(ACCESS_POINTS, SITES)  # e.g. DEF-AP-004 ← DEF-S-004

    # Compute Plus Codes
    add_plus_codes(SITES)
    add_plus_codes(TRAILS)
    add_plus_codes(ACCESS_POINTS)

    # GIS spatial lookup (township + municipality)
    add_gis_lookup(SITES)

    gps_acquired = sum(1 for s in SITES if s.get("gps_lat") is not None)
    print(f"  GPS acquired: {gps_acquired}/{len(SITES)} sites")

    # ── Stage 4.5: Vocabulary Validation Gate ────────────────────────────────
    print("\n[Stage 4.5] Vocabulary Validation Gate")
    run_vocab_gate(SITES, TRAILS, ACCESS_POINTS)

    # ── Stage 4: TSV Output ──────────────────────────────────────────────────
    print("\n[Stage 4] TSV Output")
    write_all_tsvs(
        output_dir=OUTPUT_DIR,
        prefix="defiance_oh",
        now=NOW,
        sites=SITES,
        trails=TRAILS,
        trail_segments=TRAIL_SEGMENTS,
        trail_networks=TRAIL_NETWORKS,
        site_networks=SITE_NETWORKS,
        access_points=ACCESS_POINTS,
    )

    # ── Stage 5: Integrity Check ─────────────────────────────────────────────
    print("\n[Stage 5] Integrity Check")
    warnings = integrity_check(SITES, TRAILS, ACCESS_POINTS)
    if warnings:
        for w in warnings:
            print(f"  WARNING: {w}")
    else:
        print("  No integrity issues found.")

    # ── Stage 6: Database Upsert ─────────────────────────────────────────────
    print("\n[Stage 6] Database Upsert")
    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    try:
        upsert_sites(cur, SITES, NOW, args.dry_run)
        upsert_site_parents(cur, SITES, args.dry_run)
        upsert_trails(cur, TRAILS, NOW, args.dry_run)
        upsert_trail_parents(cur, TRAILS, args.dry_run)
        upsert_access_points(cur, ACCESS_POINTS, NOW, args.dry_run)
        upsert_run_metadata(
            cur, RUN_ID, COUNTY, STATE, RUN_DATE,
            records_input=59,   # total records (entities + null results) in staging YAML
            normalized=len(SITES) + len(TRAILS) + len(ACCESS_POINTS),
            held=0,
            notes=(
                "Defiance County OH pipeline complete. "
                f"{len(SITES)} Sites, {len(TRAILS)} Trails, "
                f"{len(ACCESS_POINTS)} Access Points. "
                "Open flags: VERIFY_GOVERNANCE (DEF-S-016, DEF-AP-005), "
                "GOVERNANCE_UNCERTAIN (DEF-T-007), "
                "MINIMAL_DATA (multiple T6 village sites), "
                "DEF-F-06 UNRESOLVED (Oxbow Lake western agreement parcel)."
            ),
            now=NOW,
            dry_run=args.dry_run,
        )
        if not args.dry_run:
            conn.commit()
            print(f"  Committed {len(SITES)} sites, {len(TRAILS)} trails, "
                  f"{len(ACCESS_POINTS)} APs to {os.path.basename(args.db)}")
    except Exception as e:
        conn.rollback()
        print(f"  ERROR during upsert: {e}", file=sys.stderr)
        raise
    finally:
        conn.close()

    print("\n" + "=" * 60)
    print("PIPELINE COMPLETE")
    print(f"  Sites:          {len(SITES)}")
    print(f"  Trails:         {len(TRAILS)}")
    print(f"  Trail Segments: {len(TRAIL_SEGMENTS)}")
    print(f"  Trail Networks: {len(TRAIL_NETWORKS)}")
    print(f"  Site Networks:  {len(SITE_NETWORKS)}")
    print(f"  Access Points:  {len(ACCESS_POINTS)}")
    gps_missing = [s["site_id"] for s in SITES if s.get("gps_lat") is None]
    if gps_missing:
        print(f"  Sites still missing GPS: {', '.join(gps_missing)}")
    print("=" * 60)


if __name__ == "__main__":
    main()
